language: c
 
install:
  - sudo .travis/setup_travis.sh
  - .travis/write_local_config.sh
script:
  - cd RestClientCs
  - xbuild RestClientCs.csproj
  - nunit-console -run=RestClientCs bin/Debug/RestClientCs.dll
  - cat TestResult.xml
