language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console --fix-missing
script:
  - cd RestClientCs && xbuild RestClientCs.csproj
  - cd RestClientCs && nunit-console -run=RestClientCs bin/Debug/RestClientCs.dll
  - cd RestClientCs && cat TestResult.xml
