language: c
 
install:
  - sudo .travis/setup_travis.sh
script:
  - export TEST_SERVER_URL=http://localhost:8080`pwd`/.travis/echo.php
  - cd RestClientCs
  - xbuild RestClientCs.csproj
  - nunit-console -run=RestClientCs bin/Debug/RestClientCs.dll
  - cat TestResult.xml
